### ISSUE TITLE
.drupdate.yml file ignored

### ISSUE THREAD

**Issue by stefankim** [drupdateio/drupdate#1]
Hi,

Firstly, thanks for the great Github application.
We have enabled the Github application with .drupdate.yml file, where we want only security updates (the security_only: true is uncommented), but it creating PR for all module updates, even if it is not just security update.

**Comment by guillaumev** [comment]
Hi Stefan,
You are totally right, the security_only parameter was actually being ignored. I believe the issue should be fixed now however, and the repository (ies) you configured with drupdate.io should now only get security updates.
Feel free to send me your feedback !
Thank you.
Guillaume

**Comment by stefankim** [comment]
Hi Guillaume,

This seems to be working now. Thank you for the quick fix.
Regards,

Stefan
